name: publish-posts

on:
  push:
    branches: [ main ]
    paths: 
       - 'content/posts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: | 
          pip install -r src/requirements.txt
          python src/convert_posts_md_to_json.py
      - name: Commit JSON to repository
        run: |
          git config --global user.name 'arminfischer'
          git config --global user.email 'arminfischer@users.noreply.github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Committed .json" && git push
      - name: Reset API cache
        run: curl -X POST https://misantropolis-api.azurewebsites.net/api/resetcache