name: publish-posts

on:
  push:
    branches: [ main ]
    paths: 
       - 'content/posts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: | 
          pip install -r src/requirements.txt
          python src/convert_posts_md_to_json.py
      - name: Commit JSON to repository
        run: |
          git config --global user.name 'arminfischer'
          git config --global user.email 'arminfischer@users.noreply.github.com'
          git commit -am "Committed .json"
          git push